package com.example.demo.entities;// default package

// Generated Oct 15, 2025, 4:39:38 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * AccountStatuses generated by hbm2java
 */
@Entity
@Table(name = "account_statuses", uniqueConstraints = @UniqueConstraint(columnNames = "status_code"))
public class AccountStatuses implements java.io.Serializable {

	private Integer id;
	private String statusCode;
	private String statusName;
	private String description;
	private Set<Accounts> accountses = new HashSet<Accounts>(0);

	public AccountStatuses() {
	}

	public AccountStatuses(String statusCode, String statusName) {
		this.statusCode = statusCode;
		this.statusName = statusName;
	}

	public AccountStatuses(String statusCode, String statusName, String description, Set<Accounts> accountses) {
		this.statusCode = statusCode;
		this.statusName = statusName;
		this.description = description;
		this.accountses = accountses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "status_code", unique = true, nullable = false, length = 20)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "status_name", nullable = false, length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountStatuses")
	public Set<Accounts> getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set<Accounts> accountses) {
		this.accountses = accountses;
	}

}
