package com.example.demo.entities;// default package

// Generated Oct 15, 2025, 4:39:38 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * TransactionTypes generated by hbm2java
 */
@Entity
@Table(name = "transaction_types", uniqueConstraints = @UniqueConstraint(columnNames = "type_code"))
public class TransactionTypes implements java.io.Serializable {

	private Integer id;
	private String typeCode;
	private String typeName;
	private String description;
	private Set<TransactionFees> transactionFeeses = new HashSet<TransactionFees>(0);
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);

	public TransactionTypes() {
	}

	public TransactionTypes(String typeCode, String typeName) {
		this.typeCode = typeCode;
		this.typeName = typeName;
	}

	public TransactionTypes(String typeCode, String typeName, String description,
			Set<TransactionFees> transactionFeeses, Set<Transactions> transactionses) {
		this.typeCode = typeCode;
		this.typeName = typeName;
		this.description = description;
		this.transactionFeeses = transactionFeeses;
		this.transactionses = transactionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type_code", unique = true, nullable = false, length = 20)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_name", nullable = false, length = 50)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionTypes")
	public Set<TransactionFees> getTransactionFeeses() {
		return this.transactionFeeses;
	}

	public void setTransactionFeeses(Set<TransactionFees> transactionFeeses) {
		this.transactionFeeses = transactionFeeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionTypes")
	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

}
