package com.example.demo.entities;// default package

// Generated Oct 15, 2025, 4:39:38 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name = "transactions", uniqueConstraints = @UniqueConstraint(columnNames = "transaction_code"))
public class Transactions implements java.io.Serializable {

	private Long id;
	private Accounts accountsByFromAccountId;
	private Accounts accountsByToAccountId;
	private TransactionStatuses transactionStatuses;
	private TransactionTypes transactionTypes;
	private String transactionCode;
	private BigDecimal amount;
	private String description;
	private String beneficiaryName;
	private String beneficiaryAccount;
	private Date createdAt;

	public Transactions() {
	}

	public Transactions(TransactionStatuses transactionStatuses, TransactionTypes transactionTypes,
			String transactionCode, BigDecimal amount, Date createdAt) {
		this.transactionStatuses = transactionStatuses;
		this.transactionTypes = transactionTypes;
		this.transactionCode = transactionCode;
		this.amount = amount;
		this.createdAt = createdAt;
	}

	public Transactions(Accounts accountsByFromAccountId, Accounts accountsByToAccountId,
			TransactionStatuses transactionStatuses, TransactionTypes transactionTypes, String transactionCode,
			BigDecimal amount, String description, String beneficiaryName, String beneficiaryAccount, Date createdAt) {
		this.accountsByFromAccountId = accountsByFromAccountId;
		this.accountsByToAccountId = accountsByToAccountId;
		this.transactionStatuses = transactionStatuses;
		this.transactionTypes = transactionTypes;
		this.transactionCode = transactionCode;
		this.amount = amount;
		this.description = description;
		this.beneficiaryName = beneficiaryName;
		this.beneficiaryAccount = beneficiaryAccount;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_account_id")
	public Accounts getAccountsByFromAccountId() {
		return this.accountsByFromAccountId;
	}

	public void setAccountsByFromAccountId(Accounts accountsByFromAccountId) {
		this.accountsByFromAccountId = accountsByFromAccountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_account_id")
	public Accounts getAccountsByToAccountId() {
		return this.accountsByToAccountId;
	}

	public void setAccountsByToAccountId(Accounts accountsByToAccountId) {
		this.accountsByToAccountId = accountsByToAccountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public TransactionStatuses getTransactionStatuses() {
		return this.transactionStatuses;
	}

	public void setTransactionStatuses(TransactionStatuses transactionStatuses) {
		this.transactionStatuses = transactionStatuses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transaction_type_id", nullable = false)
	public TransactionTypes getTransactionTypes() {
		return this.transactionTypes;
	}

	public void setTransactionTypes(TransactionTypes transactionTypes) {
		this.transactionTypes = transactionTypes;
	}

	@Column(name = "transaction_code", unique = true, nullable = false, length = 50)
	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	@Column(name = "amount", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "beneficiary_name", length = 100)
	public String getBeneficiaryName() {
		return this.beneficiaryName;
	}

	public void setBeneficiaryName(String beneficiaryName) {
		this.beneficiaryName = beneficiaryName;
	}

	@Column(name = "beneficiary_account", length = 20)
	public String getBeneficiaryAccount() {
		return this.beneficiaryAccount;
	}

	public void setBeneficiaryAccount(String beneficiaryAccount) {
		this.beneficiaryAccount = beneficiaryAccount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
